apiVersion: tekton.dev/v1
kind: PipelineRun

metadata:
  generateName: tekton-demo-run-

spec:

  pipelineRef:
    name: tekton-demo-pipeline


  params:


    - name: repo-url

      value: https://github.com/filippo-colli/tekton-demo.git


    - name: image-version

      value: "v5"


    - name: image-name

      value: filicolli/nginx-demo


    - name: app-name

      value: tekton-demo



  workspaces:


    - name: shared-workspace

      persistentVolumeClaim:

        claimName: tekton-workspace