apiVersion: tekton.dev/v1
kind: Task

metadata:
  name: git-clone-task

spec:

  params:

    - name: repo-url
      type: string
      description: Repository Git da clonare


  workspaces:

    - name: shared-workspace


  steps:

    - name: clone

      image: alpine/git:v2.45.2

      script: |
        #!/bin/sh
        set -ex

        cd $(workspaces.shared-workspace.path)

        echo "Pulizia completa workspace"

        rm -rf ./*

        rm -rf ./.??* || true


        echo "Contenuto dopo pulizia"

        ls -la


        echo "Clono repository"

        git clone $(params.repo-url) .


        echo "Repository clonato"

        ls -la