apiVersion: tekton.dev/v1
kind: TaskRun

metadata:
  name: kaniko-build-test

spec:

  taskRef:
    name: kaniko-build-task

  params:

    - name: IMAGE
      value: filicolli/nginx-demo:v3


  workspaces:

    - name: source

      persistentVolumeClaim:

        claimName: tekton-workspace